=== TUMFTM/UrbanEV/dtd/chargers.dtd
<?xml version="1.0" encoding="utf-8"?>

        <!ELEMENT chargers (charger)*>

        <!ELEMENT charger EMPTY>

        <!-- x - x coordinate of the charger -->
        <!-- y - y coordinate of the charger -->
        <!-- plug_power - in kWh -->
        <!-- plug_count - number of plugs; 1 if not provided -->
        <!-- allowed_vehicles - ids of allowed vehicles (e.g. "1,2,4"); "all" if not provided -->
        <!ATTLIST charger
                id CDATA #REQUIRED
                x CDATA #REQUIRED
                y CDATA #REQUIRED
                plug_power CDATA #REQUIRED
                plug_count CDATA #IMPLIED
                type CDATA #IMPLIED
                allowed_vehicles CDATA #IMPLIED >

=== TUMFTM/UrbanEV/scenarios/munich/chargers.xml
<?xml version="1.0" ?>
<!DOCTYPE chargers
  SYSTEM '../dtd/chargers.dtd'>
<chargers>
	<charger id="401301237" x="4468413.2" y="5335744.5" plug_power="22" plug_count="2"/>
	<charger id="1475946405" x="4465700.2" y="5335126.6" plug_power="22" plug_count="2"/>
	<charger id="2409259910" x="4468501.6" y="5335347.8" plug_power="22" plug_count="2"/>
	<charger id="2413225221" x="4467197.6" y="5334163.8" plug_power="22" plug_count="2"/>
	<charger id="2415163823" x="4466993.4" y="5335432.9" plug_power="22" plug_count="2"/>
	<charger id="2590211683" x="4467803.8" y="5337540.8" plug_power="22" plug_count="2"/>
	<charger id="2610743040" x="4468348.0" y="5338724.9" plug_power="22" plug_count="2"/>
	<charger id="2787301365" x="4467138.5" y="5335809.5" plug_power="22" plug_count="2"/>
	<charger id="3112416816" x="4469055.3" y="5331896.2" plug_power="22" plug_count="2"/>
	<charger id="3303767959" x="4471112.0" y="5332336.0" plug_power="22" plug_count="2"/>
	<charger id="3639585533" x="4464159.0" y="5332933.5" plug_power="22" plug_count="2"/>
	<charger id="4249905486" x="4478126.1" y="5332967.9" plug_power="22" plug_count="2"/>
	<charger id="4249905487" x="4471844.7" y="5335126.2" plug_power="22" plug_count="2"/>
	<charger id="4251105854" x="4478126.2" y="5332961.2" plug_power="22" plug_count="2"/>
	<charger id="4775254568" x="4468898.0" y="5330912.1" plug_power="22" plug_count="2"/>
	<charger id="4890326221" x="4465400.4" y="5335216.6" plug_power="22" plug_count="2"/>
	<charger id="4929109732" x="4467051.0" y="5335337.3" plug_power="22" plug_count="2"/>
	<charger id="4939033442" x="4470488.5" y="5332956.9" plug_power="22" plug_count="2"/>
	<charger id="4939033539" x="4470487.0" y="5332947.2" plug_power="22" plug_count="2"/>
	<charger id="4955396902" x="4470680.7" y="5333559.9" plug_power="22" plug_count="2"/>
	<charger id="5081516594" x="4467758.4" y="5335129.7" plug_power="22" plug_count="2"/>
	<charger id="5113266379" x="4468666.3" y="5330339.9" plug_power="22" plug_count="2"/>
	<charger id="5113266380" x="4468658.4" y="5330333.8" plug_power="22" plug_count="2"/>
	<charger id="5137045765" x="4470555.6" y="5338083.5" plug_power="22" plug_count="2"/>
	<charger id="5137051052" x="4470548.4" y="5338090.0" plug_power="22" plug_count="2"/>
	<charger id="5137051056" x="4470113.2" y="5338516.3" plug_power="22" plug_count="2"/>
	<charger id="5176528213" x="4466474.8" y="5329427.8" plug_power="22" plug_count="2"/>
	<charger id="5176529131" x="4466324.8" y="5329527.7" plug_power="22" plug_count="2"/>
	<charger id="5176529136" x="4464834.6" y="5328914.9" plug_power="22" plug_count="2"/>
	<charger id="5176529262" x="4464842.7" y="5328915.1" plug_power="22" plug_count="2"/>
	<charger id="5176535632" x="4469033.5" y="5332770.0" plug_power="22" plug_count="2"/>
	<charger id="5176535633" x="4469084.9" y="5332841.1" plug_power="22" plug_count="2"/>
	<charger id="5176771605" x="4468126.9" y="5330641.0" plug_power="22" plug_count="2"/>
	<charger id="5179566337" x="4473658.0" y="5327731.5" plug_power="22" plug_count="2"/>
	<charger id="5179568441" x="4473651.6" y="5329001.1" plug_power="22" plug_count="2"/>
	<charger id="5179568541" x="4469355.2" y="5333788.3" plug_power="22" plug_count="2"/>
	<charger id="5179568545" x="4473659.7" y="5327721.3" plug_power="22" plug_count="2"/>
	<charger id="5179568546" x="4473647.8" y="5328991.5" plug_power="22" plug_count="2"/>
	<charger id="5179568803" x="4469350.3" y="5333789.1" plug_power="22" plug_count="2"/>
	<charger id="5179569145" x="4472614.9" y="5329267.3" plug_power="22" plug_count="2"/>
	<charger id="5179569146" x="4472615.3" y="5329270.2" plug_power="22" plug_count="2"/>
	<charger id="5182601543" x="4464804.8" y="5330966.7" plug_power="22" plug_count="2"/>
	<charger id="5182601544" x="4464804.4" y="5330977.3" plug_power="22" plug_count="2"/>
	<charger id="5196580623" x="4471892.5" y="5339368.1" plug_power="22" plug_count="2"/>
	<charger id="5196580624" x="4471884.5" y="5339370.6" plug_power="22" plug_count="2"/>
	<charger id="5201752312" x="4465416.7" y="5330622.4" plug_power="22" plug_count="2"/>
	<charger id="5201754295" x="4465424.9" y="5330622.7" plug_power="22" plug_count="2"/>
	<charger id="5207346420" x="4468891.0" y="5328876.3" plug_power="22" plug_count="2"/>
	<charger id="5207350624" x="4468896.0" y="5328886.1" plug_power="22" plug_count="2"/>
	<charger id="5230458361" x="4475641.6" y="5331533.3" plug_power="22" plug_count="2"/>
	<charger id="5285375275" x="4468373.6" y="5338107.5" plug_power="22" plug_count="2"/>
	<charger id="5289269868" x="4468742.0" y="5331618.2" plug_power="22" plug_count="2"/>
	<charger id="5289272122" x="4468738.0" y="5331613.2" plug_power="22" plug_count="2"/>
	<charger id="5289276712" x="4469892.4" y="5332415.7" plug_power="22" plug_count="2"/>
	<charger id="5289276713" x="4469889.0" y="5332411.9" plug_power="22" plug_count="2"/>
	<charger id="5289287716" x="4470220.2" y="5332213.2" plug_power="22" plug_count="2"/>
	<charger id="5289287717" x="4470217.1" y="5332210.6" plug_power="22" plug_count="2"/>
	<charger id="5300000948" x="4468578.0" y="5332899.7" plug_power="22" plug_count="2"/>
	<charger id="5300000949" x="4468578.5" y="5332905.3" plug_power="22" plug_count="2"/>
	<charger id="5300000958" x="4471519.5" y="5333887.3" plug_power="22" plug_count="2"/>
	<charger id="5300000959" x="4471512.0" y="5333888.5" plug_power="22" plug_count="2"/>
	<charger id="5376361251" x="4472002.9" y="5331457.0" plug_power="22" plug_count="2"/>
	<charger id="5376361252" x="4472010.4" y="5331464.2" plug_power="22" plug_count="2"/>
	<charger id="5394122125" x="4469067.7" y="5330915.4" plug_power="22" plug_count="2"/>
	<charger id="5394122126" x="4469069.7" y="5330925.7" plug_power="22" plug_count="2"/>
	<charger id="5415037934" x="4473628.4" y="5331827.3" plug_power="22" plug_count="2"/>
	<charger id="5420135702" x="4467133.7" y="5341830.0" plug_power="22" plug_count="2"/>
	<charger id="5420135703" x="4467132.0" y="5341819.8" plug_power="22" plug_count="2"/>
	<charger id="5437309048" x="4461529.0" y="5338540.1" plug_power="22" plug_count="2"/>
	<charger id="5437494228" x="4461067.1" y="5336319.3" plug_power="22" plug_count="2"/>
	<charger id="5437506965" x="4460377.1" y="5339506.6" plug_power="22" plug_count="2"/>
	<charger id="5462938400" x="4468877.3" y="5333150.8" plug_power="22" plug_count="2"/>
	<charger id="5516038929" x="4468835.5" y="5333077.3" plug_power="22" plug_count="2"/>
	<charger id="5516038930" x="4468845.7" y="5333075.6" plug_power="22" plug_count="2"/>
	<charger id="5516038935" x="4471039.8" y="5331179.6" plug_power="22" plug_count="2"/>
	<charger id="5516038936" x="4471032.3" y="5331172.5" plug_power="22" plug_count="2"/>
	<charger id="5519285725" x="4467870.3" y="5333415.1" plug_power="22" plug_count="2"/>
	<charger id="5519285726" x="4467880.3" y="5333412.5" plug_power="22" plug_count="2"/>
	<charger id="5519285731" x="4468214.5" y="5333683.7" plug_power="22" plug_count="2"/>
	<charger id="5519285732" x="4468204.7" y="5333687.0" plug_power="22" plug_count="2"/>
	<charger id="5519285737" x="4468922.7" y="5333508.0" plug_power="22" plug_count="2"/>
	<charger id="5519285738" x="4468912.7" y="5333510.7" plug_power="22" plug_count="2"/>
	<charger id="5539187643" x="4469638.5" y="5336202.2" plug_power="22" plug_count="2"/>
	<charger id="5600000621" x="4467350.2" y="5335294.6" plug_power="22" plug_count="2"/>
	<charger id="5602488703" x="4468698.3" y="5336961.5" plug_power="22" plug_count="2"/>
	<charger id="5602488704" x="4469254.5" y="5337103.7" plug_power="22" plug_count="2"/>
	<charger id="5602488705" x="4468769.1" y="5336606.9" plug_power="22" plug_count="2"/>
	<charger id="5604952041" x="4466481.4" y="5333675.6" plug_power="22" plug_count="2"/>
	<charger id="5604952042" x="4466471.7" y="5333663.4" plug_power="22" plug_count="2"/>
	<charger id="5633472336" x="4466474.9" y="5331491.5" plug_power="22" plug_count="2"/>
	<charger id="5650490768" x="4468118.5" y="5330644.2" plug_power="22" plug_count="2"/>
	<charger id="5650490769" x="4468136.7" y="5330637.9" plug_power="22" plug_count="2"/>
	<charger id="5682184838" x="4463550.5" y="5338208.7" plug_power="22" plug_count="2"/>
	<charger id="5682184839" x="4464508.0" y="5338280.4" plug_power="22" plug_count="2"/>
	<charger id="5682184840" x="4465328.1" y="5337353.0" plug_power="22" plug_count="2"/>
	<charger id="5702939920" x="4467883.9" y="5335962.3" plug_power="22" plug_count="2"/>
	<charger id="5711527034" x="4464792.8" y="5326682.0" plug_power="22" plug_count="2"/>
	<charger id="5732432422" x="4462842.0" y="5333175.3" plug_power="22" plug_count="2"/>
	<charger id="5734443375" x="4472712.9" y="5332097.6" plug_power="22" plug_count="2"/>
	<charger id="5734443376" x="4472722.3" y="5332094.2" plug_power="22" plug_count="2"/>
	<charger id="5787436056" x="4468764.6" y="5334694.1" plug_power="22" plug_count="2"/>
	<charger id="5837016109" x="4461331.9" y="5334231.9" plug_power="22" plug_count="2"/>
	<charger id="5837017598" x="4460968.0" y="5333972.5" plug_power="22" plug_count="2"/>
	<charger id="5837021436" x="4458177.4" y="5336304.5" plug_power="22" plug_count="2"/>
	<charger id="5837026632" x="4463702.3" y="5333530.6" plug_power="22" plug_count="2"/>
	<charger id="5837030938" x="4465462.4" y="5331579.0" plug_power="22" plug_count="2"/>
	<charger id="5837066883" x="4472357.5" y="5330306.1" plug_power="22" plug_count="2"/>
	<charger id="5837075592" x="4468161.9" y="5332948.3" plug_power="22" plug_count="2"/>
	<charger id="5837082775" x="4467702.5" y="5332800.7" plug_power="22" plug_count="2"/>
	<charger id="5837085752" x="4467539.9" y="5333449.7" plug_power="22" plug_count="2"/>
	<charger id="5838803896" x="4467581.5" y="5333233.0" plug_power="22" plug_count="2"/>
	<charger id="5838805033" x="4467220.6" y="5332820.6" plug_power="22" plug_count="2"/>
	<charger id="5838814097" x="4466158.0" y="5331648.4" plug_power="22" plug_count="2"/>
